commands-aliases:
  itemskins:
    - "itemskin"
    - "is"
    - "iskins"
    - "skin"
    - "skins"

# Configuration Explanation
# (options)
#   (remove-skin-no-permission) Should we remove item skins if the player doesn't have permission to use that skin?
#   (remove-skin-except-physical-skin) Should player able to use skins even though they do not have the permission
#                                       as long as the item is skinned with physical skin?
#                                       (remove-skin-no-permission option should be enabled)
#   (preview-skin) Should we enable skin preview? (Enable or disable right click to preview skins from the GUI)
#   (physical-require-permission) Should player need skin permission to use the physical skin?
options:
  remove-skin-no-permission: false
  remove-skin-except-physical-skin: false
  preview-skin: true
  physical-require-permission: true
  # Show skins on player's hand on skins menu open
  show-hand-skin: false

# List of blacklisted slimefun items
# If item is listed in here, the item cannot be skinned
# (all texts must be on lowercases)
blacklisted-slimefun-items:
  - "sword_of_beheading"

# The skin remover item details
skin-remover:
  material: LEATHER
  custom-model-data: 7608
  display-name: "&eSkin Remover"
  glowing: false
  lore:
    - "&7Drag & Drop this item to the"
    - "&7item that has skin!"

messages:
  prefix: "&e[Skins]"
  noPermission: "{prefix} &cYou don't have enough permission!"
  reload: "{prefix} &aYou have reloaded the configuration!"
  playerNotFound: "{prefix} &cThe player is not online!"
  mustInt: "{prefix} &cThe amount must be a number/integer!"
  materialNotFound: "{prefix} &cThere is no skin with that material!"
  skinNotFound: "{prefix} &cThere is no skin with that name!"
  itemHasSkin: "{prefix} &cThat item already have a skin!"
  itemNoSkin: "{prefix} &cThat item doesn't have any skin!"
  itemBlacklisted: "{prefix} &cThis item cannot be skinned!"
  stackable-skin-tries: "{prefix} &cYou can only do this to one item at a time!"
  preview-disabled: "{prefix} &cSkin preview is disabled on this server!"
  help:
    - "&e&lItemSkins &7- by aglerr#9849"
    - "&e/itemskins reload &7- reload the configuration"
    - "&e/itemskins physical (player) (material) (skin-name) [amount]"
    - "&e/itemskins remover (player) [amount]"
    - "&e/skins &7- open skin selector inventory"